services:
    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        arguments:
          - "@mailer"
          - 50
        class:
          - [ setLocale, [%locale%] ]
    oc_platform.twig.antispam_extension:
     class: OC\PlatformBundle\Twig\antispamExtension
     arguments:
         - "@oc_platform.antispam"
    oc_platform.form.ckeditor:
     class: OC\PlatformBundle\Form\CkeditorType
     tags:
       - { name: form.type, alias: ckeditor }
    oc_platform.beta.html_adder:
     class: OC\PlatformBundle\Beta\BetaHTMLAdder
    oc_platform.beta.listener:
     class: OC\PlatformBundle\Beta\BetaListener
     arguments:
       - "@oc_platform.beta.html_adder" 
       - "2017-06-01"
     tags:
       - { name: kernel.event_listener, event: kernel.response,   method: processBeta, priority: 2 }
       - { name: kernel.event_listener, event: kernel.controller, method: ignoreBeta }
    oc_platform.bigbrother.message_notificator:
      class: OC\PlatformBundle\Bigbrother\MessageNotificator
      arguments:
        - "@mailer"
    oc_platform.bigbrother.message_listener:
      class: OC\PlatformBundle\Bigbrother\MessageListener
      arguments:
        - "@oc_platform.bigbrother.message_notificator"
        - ["alexandre", "marine", "pierre"]
      tags:
        - { name: kernel.event_listener, event: oc_platform.post_message, method: processMessage }