<?php

namespace ASG\AlphasourcingBundle\Repository;

/**
 * PartenairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartenairesRepository extends \Doctrine\ORM\EntityRepository
{
}
